---
- name: Install package for Apache
  yum: name=httpd state=latest

- name: Install package for SSL Apache
  yum: name=mod_ssl state=latest

- name: start Apache
  service: name=httpd state=started enabled=yes

- name: Allow HTTP and HTTPS ports
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
    - "{{ 443 }}"
  notify:
    - restart Firewall

- name: Virtual Host Config
  template:
    src: zabbix-vhost.j2
    dest: /etc/httpd/conf.d/{{ inventory_hostname }}.conf
    owner: apache
    group: apache
    mode: 0640

- name: Check if ipa-client is installed
  command: rpm -q ipa-client
  register: ipa_client

- name: Kinit IPA 
  shell: echo "{{ ipaclient_password }}" | kinit {{ ipaclient_principal }}
  when: ipa_client.rc == 0

- name: Generate cert from FreeIPA
  ignore_errors: True
  command: ipa-getcert request -r -f /etc/pki/tls/certs/{{ inventory_hostname }}.crt -k /etc/pki/tls/private/{{ inventory_hostname }}.key -N  CN={{ inventory_hostname }} -D {{ inventory_hostname }} -K HTTP/{{ inventory_hostname }}
  when: ipa_client.rc == 0

- name: Generate Private Key via OpenSSL
  openssl_privatekey:
    path: /etc/pki/tls/private/{{ inventory_hostname }}.key
  when: ipa_client.rc == 1

- name: Generate CSR via OpenSSL
  openssl_csr:
    path: /etc/pki/tls/certs/{{ inventory_hostname }}.csr
    privatekey_path: /etc/pki/tls/private/{{ inventory_hostname }}.key
    country_name: {{ country_domain }}
    organization_name: {{ org_name }}
    common_name: {{ inventory_hostname }}
  when: ipa_client.rc == 1

- name: Generate Certs via OpenSSL
  openssl_certificate:
    path: /etc/pki/tls/certs/{{ inventory_hostname }}.crt
    privatekey_path: /etc/pki/tls/private/{{ inventory_hostname }}.key
    csr_path: /etc/pki/tls/certs/{{ inventory_hostname }}.csr
    provider: selfsigned
  when: ipa_client.rc == 1
  notify:
    - restart Apache
