---
- name: Enable Zabbix Repo
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    disable_gpg_check: yes
    state: present

- name: Install Zabbix Packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - zabbix-get
    - zabbix-agent
    - zabbix-web-mysql
    - zabbix-server-mysql

- name: Import sql in database 1
  ignore_errors: yes
  command: zcat /usr/share/doc/zabbix-server-mysql-4.0.4/create.sql.gz | mysql -u{{ mysql_user }} -p"'{{ mysql_user_password }}'" zabbix
  

- name: Copy Zabbix Server config file
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: zabbix
    group: zabbix
    mode: 0640

- name: Copy Zabbix Server HTTP config file
  template:
    src: zabbix_server_http_conf.j2
    dest: /etc/httpd/conf.d/zabbix.conf
    owner: apache
    group: apache
    mode: 0640

- name: Copy Zabbix Agent config file
  template:
    src: zabbix_agent.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: zabbix
    group: zabbix
    mode: 0640
  notify:
    - restart Apache

- name: Allow zabbix ports
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
    - "{{ 10050 }}"
    - "{{ 10051 }}"
  notify:
    - restart Firewall

- name: Selinux disable during start agent
  command: setenforce 0

- name: start Zabbix Server 
  service: name=zabbix-server state=restarted enabled=yes

- name: start Zabbix Agent
  service: name=zabbix-agent state=restarted enabled=yes

- name: Selinux enable after start agent
  command: setenforce 1

