---
- name: Install package for policycoreutils
  yum: name=policycoreutils-python state=latest

- name: Transfer the script
  copy: src=../../files/zabbix-selinux.sh dest=/root mode=0755
  
- name: Execute the script
  command: bash /root/zabbix-selinux.sh

- name: start firewalld
  service: name=firewalld state=restarted enabled=yes  
  
- name: start Zabbix Agent
  service: name=zabbix-agent state=restarted enabled=yes
