---
- name: Install IPA Server packages 
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - ipa-server
    - ipa-server-dns
    - bind-dyndb-ldap
    - bind-utils
    - bind  

- name: Run the installer IPA server
  command: > 
    {{ ipaserver_base_command }} 
    --realm {{ ipaserver_realm }} 
    --domain {{ ipaserver_domain }} 
    -a {{ ipaserver_admin_password }} 
    -p {{ ipaserver_dir_admin_password }} 
    --hostname={{ ipa_server_hostname }} 
    --ip-address={{ ipa_server_ip_address }} 
    {{ '--idstart=%s' % ipaserver_idstart if ipaserver_idstart | default(False) else '' }} 
    {{ '--idmax=%s' % ipaserver_idmax if ipaserver_idmax | default(False) else '' }} 
    --no-forwarders
    {{ '--mkhomedir' if ipaserver_mkhomedir | default(True) else '' }} 
    {{ '--setup-dns' if ipaserver_setup_dns | default(True) else '' }} 
    {{ '--ssh-trust-dns' if ipaserver_ssh_trust_dns | default(True) else '' }} 
    {{ '' if ipaserver_hbac_allow | default(True) else '--no_hbac_allow' }} 
    {{ '' if ipaserver_setup_ntp | default(True) else '--no-ntp' }} 
    {{ '' if ipaserver_configure_ssh | default(True) else '--no-ssh' }} 
    {{ '' if ipaserver_configure_sshd | default(True) else '--no-sshd' }} 
    {{ '' if ipaserver_ui_redirect | default(True) else '--no-ui-redirect' }} 
  args: 
    creates: /etc/ipa/default1.conf


