---
- name: Install deb in Debian 9 (stretch)
  get_url:
    url: https://repo.zabbix.com/zabbix/4.0/debian/pool/main/z/zabbix-release/zabbix-release_4.0-2+​stretch_all.deb
    dest: /root/zabbix-release_4.0-2+​stretch_all.deb
    mode: 0755
  when: ansible_distribution == 'Debian'

- name: Install a .deb package
  apt:
    deb: /root/zabbix-release_4.0-2+​stretch_all.deb
  when: ansible_distribution == 'Debian'

- name: Install deb in Ubuntu 18.04 (bionic)
  get_url:
    url: https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb
    dest: /root/zabbix-release_4.0-2+bionic_all.deb
    mode: 0755
  when: ansible_distribution == 'Ubuntu'

- name: Install a .deb package
  apt:
    deb: /root/zabbix-release_4.0-2+bionic_all.deb            
  when: ansible_distribution == 'Ubuntu'

- name: Update all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Install Zabbix Packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - zabbix-frontend-php
    - zabbix-server-mysql
    - zabbix-agent

- name: Import sql in database 1
  ignore_errors: yes
  command: zcat /usr/share/doc/zabbix-server-mysql-4.0.4/create.sql.gz | mysql -u{{ mysql_user }} -p"'{{ mysql_user_password }}'" zabbix

- name: Copy Zabbix Server config file
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: zabbix
    group: zabbix
    mode: 0640

- name: Copy Zabbix Server HTTP config file
  template:
    src: zabbix_server_http_conf.j2
    dest: /etc/apache2/conf-enabled/zabbix.conf
    owner: apache
    group: apache
    mode: 0640

- name: Copy Zabbix Agent config file
  template:
    src: zabbix_agent.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: zabbix
    group: zabbix
    mode: 0640

- name: Allow zabbix ports
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
    - "{{ 10050 }}"
    - "{{ 10051 }}"
  notify:
    - restart Firewall

- name: start Zabbix Server 
  systemd: name=zabbix-server state=restarted enabled=yes

- name: start Zabbix Agent
  systemd: name=zabbix-agent state=restarted enabled=yes

- name: Restart Apache
  systemd: name=apache2 state=restarted
