---
- name: Transfer the script
  copy: src=../../files/php72-for-deb.sh dest=/root mode=0755
  
- name: Execute the script
  command: bash /root/php72-for-deb.sh

- name: replace line
  lineinfile: 
    dest: /etc/php/7.2/apache2/php.ini
    regexp: ';date.timezone =' 
    line: 'date.timezone = "{{ your_timezone }}"'
    backrefs: yes
