---
- name: Install package Firewall
  apt:
    name: firewalld
    state: present

- name: start Firewall
  service: name=firewalld state=started enabled=yes

- name: Allow zabbix ports
  command: firewall-cmd --permanent --add-port={{ item }}/tcp
  with_items:
    - "{{ 10050 }}"
    - "{{ 10051 }}"
  notify:
    - restart Firewall

- name: Install deb in Debian 9 (stretch)
  get_url:
    url: https://repo.zabbix.com/zabbix/4.0/debian/pool/main/z/zabbix-release/zabbix-release_4.0-2+​stretch_all.deb
    dest: /root/zabbix-release_4.0-2+​stretch_all.deb
    mode: 0755
  when: ansible_distribution == 'Debian'

- name: Install a .deb package
  apt:
    deb: /root/zabbix-release_4.0-2+​stretch_all.deb
  when: ansible_distribution == 'Debian'

- name: Install deb in Ubuntu 18.04 (bionic)
  get_url:
    url: https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb
    dest: /root/zabbix-release_4.0-2+bionic_all.deb
    mode: 0755
  when: ansible_distribution == 'Ubuntu'

- name: Install a .deb package
  apt:
    deb: /root/zabbix-release_4.0-2+bionic_all.deb            
  when: ansible_distribution == 'Ubuntu'

- name: Update all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: True

- name: Install Zabbix Packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - zabbix-agent

- name: Copy Zabbix Agent config file
  template:
    src: zabbix_agent.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: zabbix
    group: zabbix
    mode: 0640

- name: start Zabbix Agent
  systemd: name=zabbix-agent state=restarted enabled=yes

- name: Restart Firewall
  systemd: name=firewalld state=restarted 
