---
- name: Install IPA package 
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - ipa-client

- name: Run the installer IPA client
  command: > 
    ipa-client-install
    -p {{ ipaclient_principal }}
    -w {{ ipaclient_password }}
    --hostname {{ inventory_hostname }}
    --server {{ ipaserver_hostname }}
    --domain {{ ipaclient_domain }}
    --realm {{ ipaclient_realm }}
    --enable-dns-updates
    --mkhomedir
    --unattended
    --force-join

